/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_noveo_nativeexample_utils_NDKUtils */

#ifndef _Included_com_example_noveo_nativeexample_utils_NDKUtils
#define _Included_com_example_noveo_nativeexample_utils_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_noveo_nativeexample_utils_NDKUtils
 * Method:    nativeGetMessage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_noveo_nativeexample_utils_NDKUtils_nativeGetMessage
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
